ALTER TABLE notes ADD COLUMN is_pinned INTEGER DEFAULT 0;
ALTER TABLE notes ADD COLUMN folder_id TEXT;
ALTER TABLE note_folders ADD COLUMN order_index INTEGER DEFAULT 0;
ALTER TABLE files ADD COLUMN is_pinned INTEGER DEFAULT 0;
ALTER TABLE files ADD COLUMN folder_id TEXT;
ALTER TABLE folders ADD COLUMN icon TEXT;
