ALTER TABLE tasks ADD COLUMN due TEXT;
ALTER TABLE tasks ADD COLUMN category TEXT;
ALTER TABLE tasks ADD COLUMN order_index INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN due_date TEXT;
ALTER TABLE tasks ADD COLUMN parent_id TEXT;
